before_script:
  - apt-get -qq update
  - apt-get -qq install software-properties-common
  - apt-get -qq install bc

test:ubuntu:
  image: ubuntu:15.10
  script:
    - add-apt-repository -qq -y ppa:duggan/bats
    - apt-get -qq update
    - apt-get -qq install bats
    - bats --version
    - bats ./unitTesting/tests-linux-kernel-utilities.bats

test:debian:
  image: debian
  script:
    # We are accepting the use of PPA's to simplify the install of BATS
    # for unit testing.
    - add-apt-repository -qq -y ppa:duggan/bats
    - sed -i 's/jessie/wily/g' /etc/apt/sources.list.d/duggan-bats-jessie.list
    - apt-get -qq update
    - apt-get -qq install bats
    - bats --version
    - bats ./unitTesting/tests-linux-kernel-utilities.bats