image: ubuntu

before_script:
  - apt-get -qq update
  - apt-get install software-properties-common
  - add-apt-repository -y ppa:duggan/bats
  - apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - apt-add-repository -y ppa:beineri/opt-qt56-trusty
  - apt-get -qq update
  - apt-get -qq install bats gcc make fakeroot libncurses5 libncurses5-dev kernel-package build-essential pkg-config libnotify-bin gnupg qt56tools qt56svg qt56script

bats:
  script:
    - bats ./unitTesting/tests-linux-kernel-utilities.bats
    - source /opt/qt56/bin/qt56-env.sh
