image: ubuntu

before_script:
  - apt-get -qq update
  - apt-get -qq install software-properties-common
  - add-apt-repository -y ppa:duggan/bats

# We should be able to start with a new image
all-tests:
  script:
    - bats ./unitTesting/tests-linux-kernel-utilities.bats
