before_script:
  - apt-get -qq update
  - apt-get -qq install software-properties-common
  - apt-get -qq install bc

test:ubuntu:
  image: ubuntu:15.10
  script:
    - add-apt-repository -y ppa:duggan/bats
    - apt-get -qq update
    - apt-get -qq install bats
    - bats --version
    - bats ./unitTesting/tests-linux-kernel-utilities.bats

# We are accepting the use of PPA's to simplify the install of BATS
# for unit testing.
test:debian:
  image: debian
  script:
    - add-apt-repository -y ppa:duggan/bats
    - ls -lha /etc/apt/sources.list.d/
    - cat /etc/apt/sources.list.d/duggan-ubuntu-bats-xenial.list
    - sed -i 's/debian-stretch/xenial/g' /etc/apt/sources.list.d/duggan-ubuntu-bats-xenial.list
    - apt-get -qq update
    - apt-get -qq install bats
    - bats --version
    - bats ./unitTesting/tests-linux-kernel-utilities.bats