before_script:
  - apt-get -qq update
  - apt-get -qq install bc git lsb-release whiptail 
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=$PATH:/tmp/local/bin
  - export TERM=xterm-256color
  - gem install fpm

variables:
  - export PKG_VER="1.1.2"
  - export NAME="linux-kernel-utilities"
  - export DESC="Utilities to compile & update linux kernels for Debian and deriv's (e.g. Ubuntu, LinuxMint, etc.)"
  - export URL="https://github.com/mtompkins/linux-kernel-utilities"
  - export A_INST="hooks/fpm-after-install.sh"
  - export B_REMOVE="hooks/fpm-before-uninstall.sh"
  - export MAINT="mets_dev@outlook.com"
  - export ARCH="all"

test:ubuntu:
  image: ubuntu:15.10
  script:
    - bats --version
    - bats ./unitTesting/tests-linux-kernel-utilities.bats
    - fpm -s dir -t deb -n "${NAME}" -v "${PKG_VER}" -a "${ARCH}" --deb-no-default-config-files --after-install "${A_INST}" --before-remove "${B_REMOVE}" -m "${MAINT}" --description "${DESC}" --url "${URL}" ../linux-kernel-utilities=/opt
  artifacts:
    paths:
    - linux-kernel-utilities_${PKG_VER}_${ARCH}.deb

test:debian:
  image: debian
  script:
    - bats --version
    - bats ./unitTesting/tests-linux-kernel-utilities.bats
